include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - lib/src/models/generated/**
  errors:
    avoid_catches_without_on_clauses: ignore
    avoid_positional_boolean_parameters: ignore
    cascade_invocations: ignore
    constant_identifier_names: ignore
    directives_ordering: ignore
    document_ignores: ignore
    flutter_style_todos: ignore
    lines_longer_than_80_chars: ignore
    public_member_api_docs: ignore
    use_late_for_private_fields_and_variables: ignore

linter:
  rules:
    dangling_library_doc_comments: true
    unnecessary_breaks: true
